service: leadconnect

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  environment:
    NODE_ENV: production
    PORT: 3000
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
          Resource: "*"
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  api:
    handler: server/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      DATABASE_URL: ${ssm:/leadconnect/database-url}
    timeout: 30
    memorySize: 1024

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true 